### ISSUE TITLE
globi_allNamesUpdated.csv

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/Bee-Specialization-Modeling#4]
@cmsmith91 the file globi_allNamesUpdated.csv that is used in the bee phylogeny script. How was this dataset created?

I see in update_bee_names.R the input file is interactions-14dec2022.csv and the output is globi_american_native_bees_7march2023.csv

The reason I am asking is that the new phylogeny using Henriquez Piskulich et al. is missing 5 genera: Pseudopanurgus,Peponapis,Tetraloniella,Syntrichalonia,Cemolobus,Micralictoides. Looking at the taxonomy they are using in the tree, it is different different based on the new classification of Eucera. See: https://academic.oup.com/isd/article/7/4/3/7222693?login=true

Based on their taxonomy file, here are the changes:

Peponapis is now Xenoglossa (Peponapis)
Tetraloniella is now Xenoglossa (Tetraloniella)
Syntrichalonia is now Xenoglossa (Syntrichalonia)
Cemolobus is now Xenoglossa (Cemolobus)
Pseudopanurgus is now Protoandrena 

Micralictoides <- only genus missing

[BEE_Supp_file1.xlsx](https://github.com/user-attachments/files/15570710/BEE_Supp_file1.xlsx)

Question: Would you update the GloBI file to also include these changes since they are in the taxonomy file? I assume so, but need a sanity check.

**Comment by cmsmith91** [comment]
@seltmann globi_allNamesUpdated.csv was created using update_plant_names R [script](https://github.com/Big-Bee-Network/Bee-Specialization-Modeling/blob/master/scripts/update%20plant%20names.R).

That makes sense to me - if you are using a new phylogeny to update the globi and fowler datasets with the same changes. Does that help answer your questions?

**Comment by seltmann** [comment]
@cmsmith91 thanks for walking me through this! I see, you first fixed bee names then imported into plant script.

I assume I also need to update the bee list from Avery

**Comment by seltmann** [comment]
Well great news. The authors are treating Micralictoides as Dufouria so we do not need to add any taxa to the tree, it works as it is and covers all of the GloBI bees.

**Comment by seltmann** [comment]
closed
